version: "3.9"

services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - 3002:27017
    volumes:
      - /data/db
  nodejs:
    build: .
    container_name: nodejs
    command: npm run develop
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - 3001:3001
    depends_on:
      - mongo
